name: testing

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --all-features
    - name: Lint
      run: cargo clippy --all-features -- -Dwarnings -W clippy::pedantic
    - name: Test
      run: cargo test --all-features
    - name: Document
      run: cargo doc --all-features
